varone=[]
vartwo=[1,2,3,4,5]
varthree=[1,2,3,'a','b','c']
print(varone)
print(vartwo)
print(varthree)
print(max(vartwo))
print(len(varone))

print(vartwo.append(6))
print(vartwo)
print(vartwo.reverse())
print(vartwo)
print(vartwo.pop())
print(vartwo)
print(vartwo.sort())
print(vartwo)
varfeatures=[[1,2],[1,3]]
print(varfeatures)
